language: python
python:
    - 3.6
env:
    global:
        - PYTHONPATH="$TRAVIS_BUILD_DIR/_pypath:/$TRAVIS_BUILD_DIR/_pypath/nike-test"
        - LOG_PATH="$TRAVIS_BUILD_DIR/log"
before_install:
    - mkdir _pypath $LOG_PATH
install:
    - pip install -r requirements.txt
    - pip install -r test.requirements.txt
    - cd $TRAVIS_BUILD_DIR
before_script:
    - ln -s "$TRAVIS_BUILD_DIR" _pypath/nike-test
script:
    - python -m unittest discover -s tests/integration -v
    - coverage run --source=nike-test -m unittest discover -s tests/unit -v
    - coverage report
after_failure:
    - cat $LOG_PATH/*.log